name: CI

on:
  push:
    branches: main
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - uses: actions/checkout@v2
    - uses: RaoHai/yuque2Readme@master
      with:
        yuque-token: ${{secrets.YUQUE_TOKEN}}
        yuque-namespace: ccknbc/blog
        yuque-doc-public-only: true
        yuque-template-file: README.template.md
        yuque-output-file: README.md

    - name: Result
      run: |-
        cat README.md

    - uses: gautamkrishnar/blog-post-workflow@master
      with:
        feed_list: "https://blog.ccknbc.cc/rss.xml"
        max_post_count: 5
        readme_path: README.template.md
        committer_username: "github-actions[bot]"
        committer_email: "github-actions[bot]@users.noreply.github.com"

    - name: Delete Workflow Runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 1